### ISSUE TITLE
Include headers missing

### ISSUE THREAD

**Issue by nash169** [frankaemika/libfranka#65] opened 2020-06-03 09:35 UTC
Hi,
I've noticed that a couple of include headers are missing and this might break the compilation some time.

In include/franka/control_tools.h missing string
In include/franka/control_types.h missing stdexcept

**Comment by otherwiseopen** [comment] 2021-05-13 21:48
Hi,
do you plan to update the 0.8.* release and the [libfranka-release repo](https://github.com/frankaemika/libfranka-release) with this fix? Currently, it is not possible building a Franka-enabled ROS from source using the [recommended process](http://wiki.ros.org/noetic/Installation/Source) without some awkward workarounds (at least on Fedora 33/34), which is unfortunate, since the problem has been fixed for quite a while.

**Comment by AndreasKuhner** [comment] 2024-09-26 10:02
Hi @nash169 ,
I think the issue is resolved by now... if not, please open again. Thank you!

Cheers,
Andreas

**Closed by AndreasKuhner** 2024-09-26 10:02 UTC
