### ISSUE TITLE
self_collision_avoidance_violation with collision free motion plans

### ISSUE THREAD

**Issue by 5yler** [frankaemika/libfranka#23] opened 2018-09-27 21:10 UTC
We are sending the robot collision-free trajectories which perform as expected in simulation. However, when running on the physical robot, it will often stop with a `self_collision_avoidance_violation` error. We have tried replacing the mesh collision geometry in the `franka_description` URDF with cylinders/boxes and specifically increasing the cylinders around links 1 and 6 to address the problem, but the robot will still stop - see below screenshots with overlaid collision geometry in an example configuration.

![image](https://user-images.githubusercontent.com/10868851/46174667-a5998a80-c277-11e8-8f9b-5a7397bbd344.png)

![image](https://user-images.githubusercontent.com/10868851/46174715-c95cd080-c277-11e8-8d1e-6bd9334ccb4e.png)

Is there a way to disable the self collision avoidance or change parameters such that this error would not be triggered during feasible trajectories? Increasing the collision geometry even further limits reachability in our workspace.

**Comment by kribr** [comment] 2018-10-17 12:02
We are encountering the same problem as well when panda link 2 and 6 move close to one another. We have found the collision error to be reproducible, but have not found a solution yet.

**Comment by jonasTUM** [comment] 2019-07-16 10:41
Hello everybody, I just faced the same issue. Could you let me know how you proceeded with that problem?

**Comment by fwalch** [comment] 2019-07-22 12:06
In the develop branch on `franka_ros`, we updated the collision volumes to match the ones we use internally. This has not been released yet, but we'll try to do that soon. In the meantime, you can try to use the develop branch. I'll therefore close this as a duplicate of https://github.com/frankaemika/franka_ros/issues/39

**Closed by fwalch** 2019-07-22 12:06 UTC
